version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - /src/MuseApp
      - /src/MuseApp.Core
      - /tests/MuseApp.Core.Tests
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
